add docs for external-dns with designate
wiit-cloud/docs pull request #32
Opened 2024-09-24 09:47 UTC by jko-wiit

2024-09-24 10:42 UTC, qeqar commented on docs/_managedk8s/FAQ/automatic_dns/index.en.md
> +nav_order: 4000
the nav order needs to be set :-) to a different value.

The global topic gehts the X000 number and the sub topic normal XY00.

so at least 4100 would be needed here

2024-09-24 11:06 UTC, qeqar requested changes

2024-09-24 11:06 UTC, qeqar commented on docs/_managedk8s/FAQ/automatic_dns/index.en.md
> +1. Create a **gec.io** subdomain dns zone via WebGui **Project -> DNS -> Zones** for e.g. *example.gec.io*
don't use gec.io as an example, use something generic

2024-09-24 11:06 UTC, qeqar commented on docs/_managedk8s/FAQ/automatic_dns/index.en.md
> +    $ dig my-app.example.gec.io @dns1.ddns.innovo.cloud.
make clear that they need to update their main domain to delegate to designate: https://github.com/gecio/gecio.github.io/blob/6fb320cfcda9fd18a9097c90e4a382f0c4ab886e/docs/_gks/k8sapplications/externaldnsanddesignate/index.en.md?plain=1#L25-L33

2024-09-24 13:06 UTC, qeqar approved these changes

2024-09-25 07:18 UTC, hfi-wiit approved these changes

2024-09-25 07:18 UTC, merged