Update localstorage info
wiit-cloud/docs pull request #9
Opened 2024-08-15 12:20 UTC by TaraKIno

Updates L1 info

2024-08-15 12:44 UTC, TheSimonxy submitted a review, later dismissed

2024-08-20 11:25 UTC, SRv6d requested changes
Would be great to have uniform spelling, would lean towards "Flavors" since that's how OpenStack spells it.

2024-08-20 11:25 UTC, SRv6d commented on docs/_optimist/specs/flavor_specification/index.de.md
> +L1 / Localstorage-Flavours können bei <support@gec.io> angefordert werden.
```suggestion
L1 / Localstorage-Flavors können bei <support@gec.io> angefordert werden.
```

2024-08-20 11:25 UTC, SRv6d commented on docs/_optimist/storage/localstorage/index.de.md
> +L1 / Localstorage-Flavours können bei <support@gec.io> angefordert werden.
```suggestion
L1 / Localstorage-Flavors können bei <support@gec.io> angefordert werden.
```

2024-08-20 11:27 UTC, SRv6d approved these changes

2024-08-22 13:18 UTC, TheSimonxy approved these changes

2024-08-22 13:18 UTC, merged